### ISSUE TITLE
SPContentDatabase MountContentDatabase not found

### ISSUE THREAD

**Issue by typozh** [PowerShell/SharePointDsc#383]
**Details of the scenario you try and problem that is occurring:**
The resource SPContentDatabase does not work. The function at the end of the script is not found.

I added the function to Export-ModuleMember:
Export-ModuleMember -Function *-TargetResource,Mount*

Then the cmdlet Mount-SpContentDatabase is not found.

**The DSC configuration that is using the resource:**

                foreach($ContentDatabase in $webapp.ContentDatabases) {
                    $internalContentDatabaseName = $ContentDatabase.Name
                    SPContentDatabase $internalContentDatabaseName {
                        Name = ($ConfigurationData.NonNodeData.SQLServer.DatabasePrefix + $ContentDatabase.Name)
                        DatabaseServer = $ConfigurationData.NonNodeData.SQLServer.ContentDatabaseServer
                        WebAppUrl = $webApp.Url
                        Enabled = $ContentDatabase.Enabled
                        WarningSiteCount = $ContentDatabase.WarningSiteCount
                        MaximumSiteCount = $ContentDatabase.MaximumSiteCount
                        Ensure = "Present"
                        PsDscRunAsCredential = $SPSetupAccount
                    }
                }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2012R2, SharePoint 2016, WMF5 RTM

**Version of the DSC module you're using:**
SharePointDSC 1.1.0.0

**Comment by BrianFarnhill** [comment]
This was fixed in #370 which is being released as part of SharePointDsc 1.2.0.0 - the [code for that](https://github.com/PowerShell/SharePointDsc/tree/release-1.2) is complete and it's due for release to the PowerShell gallery shortly. So grab the new version when it's there and have a go with that. Thanks!

**Comment by typozh** [comment]
I'm now using version 1.2.0.0 but it still does not work. The error message is:
PowerShell DSC resource MSFT_SPContentDatabase  failed to execute Set-TargetResource functionality with error message: Error occurred while mounting content database. Content database is not mounted. Error details: The term 'Mount-SPContentDatabase' is 
not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : scw000000622.corp.gwpnet.com
 
Any ideas?
Thanks, Brian

**Comment by ykuijs** [comment]
I have made this update back in July and tested it extensively, all worked great. So not sure why it is failing on your environment. Are you sure the resource is updated on all your machines?

**Comment by BrianFarnhill** [comment]
I'm re-opening this one as we have another source that looks like it's having the same issue here on an internal piece of work. @ykuijs is looking in to this one - will update here when we have news.

**Comment by ykuijs** [comment]
Looks like this is an issue specific to SharePoint 2016. Spinning up a SharePoint 2016 environment now to test this issue.

**Comment by ykuijs** [comment]
@BrianFarnhill, Issue can be closed. Is fixed in PR415
