### ISSUE TITLE
Exception calling"AddActiveDirectoryConnection" with "10" argument(s)

### ISSUE THREAD

**Issue by jmcanally** [PowerShell/SharePointDsc#439]
**Details of the scenario you try and problem that is occurring:**
Trying to use SPUserProfileSyncConnection and getting the error below.  What am I missing?

**Error Details:**
PowerShell DSC resource MSFT_SPUserProfileSyncConnection  failed to execute Set-TargetResource functionality with error message: Exception c
"AddActiveDirectoryConnection" with "10" argument(s): "Could not load file or assembly 'Microsoft.ResourceManagement, Version=4.0.2450.51,
Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SERVER_NAME

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
OS = Win2012 R2
PS = 5

**Version of the DSC module you're using:**
1.3

**Comment by BrianFarnhill** [comment]
Good timing, I actually hit this same issue yesterday. I've found that this happens with SharePoint 2013 when it's in Active Directory Import mode (as opposed to the full profile sync mode that uses FIM) and so I suspect that this would also happen to SharePoint 2016 as well. So we need to investigate what needs to change in the script when it's not the FIM import mode and go from there. Will keep this post updated when progress gets made on this one.

**Comment by przlwo** [comment]
Hello, 
any news about this issue? I also have this issue when trying to create AD connection in SP2016.

**Comment by tseward** [comment]
If you copy C:\Program Files\Microsoft Office Servers\15.0\Synchronization Service\Bin\Microsoft.ResourceManagement.dll from a SharePoint Server 2013 installation and reference it however you need to, does it function correctly? This DLL is missing from SharePoint 2016 for obvious reasons -- UPSS no longer exists.

**Comment by przlwo** [comment]
Tank you tseward for this information. I would not prefer to copy any SP 2013 file. Do you know if there is already avaliable some PowerShell script for SP 2016 that establishes AD sync configuration?

**Comment by przlwo** [comment]
I found information that this might be possible by use "act like a user" way in PS (https://gallery.technet.microsoft.com/Create-User-Profile-Sync-e9ec0cf7). Is it the only way with PowerShell?

**Comment by BrianFarnhill** [comment]
@tseward This is 100% not supported, and if it did work, it would apply to the old FIM approach for connections and not the AD import one, so definitely lets not do that :)

@przlwo This approach "might" work, but given that the DSC processes are designed to run without a UI I wouldn't reliably count on it being able to run a UI dependent process like internet explorer. We need to find a programmatic way (through either the server side APIs or other powershell cmdlets) to achieve this.

**Comment by tseward** [comment]
@BrianFarnhill I traced through the wrong class :) Using `Add-SPProfileSyncConnection` would be the solution for those using SharePoint 2016. This cmdlet is fully supported on SharePoint 2016.

**Comment by BrianFarnhill** [comment]
@tseward I need to double check that - I know we didn't support it in 2013 but I can't find the public doco on it for 2016 either. If it got the green light then 100% yes that will be how we do it.

**Comment by tseward** [comment]
Yeah, the supportability comes from the PG. :) Confirmed late last Feb.

**Comment by BrianFarnhill** [comment]
Any chance you have a link to that in writing somewhere to save me having to chase some people down?

**Comment by typozh** [comment]
I would also need this to work for SP2016. Any update?

**Comment by typozh** [comment]
Hi @BrianFarnhill: Any update on this? I would need this for SP2016. Thanks!

**Comment by tseward** [comment]
@BrianFarnhill I sent you an email back in late January for the person to contact for supportability.

**Comment by BrianFarnhill** [comment]
Yea I got the email, and the short version is that yes we can use that command for SP2016 - it's just literally been a matter of me finding the time to write some code for this that has held it back (keeping in mind that me running this project is something I do on top of my standard day job!). If someone else wants to have a crack at this I'll help where I can to get it over the line, otherwise it's on the backlog and I'll get to it when I get the chance to write the code for it. Sorry guys

**Comment by BrianFarnhill** [comment]
OK so the issue I'm facing here is that we can't seem to retrieve details of things like what OUs have been configured on the LDAP connections (at least not that I have found in the object model for this stuff), which presents us with an issue in that we lose functionality compared to the FIM based import connections which present a little differently through the object models.

So from what I can see we have a couple of options here:

1. We fix the support for the LDAP connections in 2013 and 2016, but document that they will only test for the presences of the connection, if you deploy a new config with changed OUs or other settings you will need to manually delete it to let the DSC script recreate a new connection with the right settings on it - and the leave the FIM based connections in 2013 as is
2. We remove the functionality from the FIM based connections to make them work the same as the LDAP connections will, so we at least have some consistency between things here and all connection types behave the same

If we take option 1 we have inconsistency within the resource in terms of how connections in DSC will behave in regards to LDAP vs. FIM in SharePoint 2013 (SharePoint 2016 won't notice a difference, but keep in mind SP2013 is still a fully supported thing for us in SharePointDsc land), but if we take option 2 we get the consistency, but this falls in to breaking change territory as we are taking away something that version 1.x did, so we need to wait for v2.0 to release this in to the wild.

Also worth noting that the Add-SPProfileSyncConnection command is a separate thing here as the main method impacted by the APIs here is the get method which we need to test if the connections are in their desired state or not.

So given all that - I think my preference is to go for option 2 on this one as I think the consistency of behaviour is more important to us here, but I'm open to feedback. @ykuijs I definitely want your input on this one as well dude.

**Comment by ykuijs** [comment]
Option 2 requires you to manually configure the LDAP connection after installing the UPA, which is contradictive with the idea behind DSC. So my preference is to go with option 1 and maybe include an additional warning message in the code. That way at least you can install SP in a fully automated way.

**Comment by BrianFarnhill** [comment]
No it doesnt, it still automatically sets up the LDAP connection after installing the UPA, it just means if you change the config later (to change the OUs it imports from for example) it won't automatically update the connection for you, but the initial provisioning can be automated. Does that change your opinion on which option?

**Comment by ykuijs** [comment]
Ok, so you only want to remove the connection update functionality from the FIM import? I read your comment as removing the LDAP connection functionality all together.

If it is just removing updating the LDAP connections from FIM, then I am agree with you that we should go for option 2.

**Comment by BrianFarnhill** [comment]
No what i want to remove from the FIM option is the ability to update a connection (for the same scenario like changing OUs) so that it wont do the updates, just do the initial creation the same as it would if you were using the LDAP import mode. So then no matter what mode you have the UPA in, you get teh same behaviour of the connections from a DSC perspective

**Comment by ykuijs** [comment]
@BrianFarnhill are you working on fixing this? If so, can you also take a look at issue #551? This also involves an issue in the User Profile SA.

**Comment by sblasko4868** [comment]
Is there any fix for this? Is there a workaround to get an equivalent of `Get-SPProfileSyncConnection`? The resource specifically blocks anything other than version 15.

**Comment by ykuijs** [comment]
Hi @sblasko4868, sorry this issue has not been fixed yet. We did not have the time to work on fixing the issue yet.

**Comment by NikCharlebois** [comment]
@sblasko4868 I'll be looking at this over the next few days and keep you posted. Cheers

**Comment by NikCharlebois** [comment]
So, I managed to introduce logic to use the cmdlet for 16, but now as @BrianFarnhill mentionned above there doesn’t seem to be a way for us to retrieve the SynchronizationOU value from an ActiveDirectoryImportConnection object. You can create the connection, but can’t retrieve its info after using the object model. As Brian points out, this will leave the resource in an inconsistent state since the set-targetresource will work, but the get-targetresource won’t be able to retrieve the OU info, meaning that test-targetresource will always return false. Will continue to investigate a bit, and will ping some people to see what options are available to retrieve this info, if there’s any.

**Comment by NikCharlebois** [comment]
@BrianFarnhill the only way possible to retrieve information about the OU is to Reflect in. I scanned the entire Object Model and the only way we can retrieve this info is by calling internal methods. The following lines of code will give us the information we were looking for. It exposes the connection information, including the OU details for an ActiveDirectoryImportConnection object:

$BINDING_FLAGS = ([System.Reflection.BindingFlags]::NonPublic -bOr [System.Reflection.BindingFlags]::Instance)

 $connection = $upcm.ConnectionManager | Where-Object -FilterScript { 
            $_.DisplayName -eq $params.Name
        } | Select-Object -first 1

$conn = $connection.Parent.Item($params.Name)

$METHOD_GET_NAMINGCONTEXTS = [Microsoft.Office.Server.UserProfiles.ActiveDirectoryImportConnection].GetMethod("get_NamingContexts", $BINDING_FLAGS)
$METHOD_GET_NAMINGCONTEXTS.Invoke($connection.Parent.Item(0), $null)

**Comment by BrianFarnhill** [comment]
@NikCharlebois My standing rule of reflection is that we can do it as a last resort to read properties, but never to set anything. So assuming that all we see in the code review I'm ok with it.

**Comment by ykuijs** [comment]
Agree with Brian, that is how we do it in several other resources as well

**Comment by NikCharlebois** [comment]
Yep, my thoughts exactly as well. Great then!

**Comment by ykuijs** [comment]
Fixed in PR #684

**Comment by luigilink** [comment]
The problem still exists on SharePoint 2013:

`COMMENTAIRES : [SPS15DEV01]: LCM:  [ Start  Resource ]  [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp]
COMMENTAIRES : [SPS15DEV01]: LCM:  [ Start  Test     ]  [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp]
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Importing the module MSFT_SPUserProfileServiceApp in for
ce mode.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Importing the module MSFT_SPUserProfileServiceApp in for
ce mode.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Testing for user profile service application SCWZUDA0SPS
UPS
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Getting user profile service application SCWZUDA0SPSUPS
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Executing as the local run as user CHLOROPHYLLE\CSAPTTD1
0SPSFFP
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving BeginProcessing Method of Get-SPFarm.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving ProcessRecord Method of Get-SPFarm.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving EndProcessing Method of Get-SPFarm.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving BeginProcessing Method of Get-SPManagedAccount.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving ProcessRecord Method of Get-SPManagedAccount.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving EndProcessing Method of Get-SPManagedAccount.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Executing as the local run as user CHLOROPHYLLE\CSAPTTD1
0SPSFFP
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplicati
on.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication
.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication
.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving BeginProcessing Method of Get-SPServiceApplicati
onProxy.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving ProcessRecord Method of Get-SPServiceApplication
Proxy.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving EndProcessing Method of Get-SPServiceApplication
Proxy.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving BeginProcessing Method of Get-SPWebApplication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving ProcessRecord Method of Get-SPWebApplication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving EndProcessing Method of Get-SPWebApplication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving BeginProcessing Method of Get-SPServiceContext.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving ProcessRecord Method of Get-SPServiceContext.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Leaving EndProcessing Method of Get-SPServiceContext.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Current Values: ApplicationPool=SharePoint Service Appli
cations; EnableNetBIOS=False; Ensure=Present; InstallAccount=; MySiteHostLocation=http://sp
s15dev01:80/; MySiteManagedPath=personal; Name=SCWZUDA0SPSUPS; NoILMUsed=True; ProfileDBNam
e=DZUDA0SPSUSP; ProfileDBServer=ZUDA0-SPSSQL; ProxyName=SCWZUDA0SPSUPS; SiteNamingConflictR
esolution=Username_CollisionError; SocialDBName=DZUDA0SPSUMY; SocialDBServer=ZUDA0-SPSSQL; 
SyncDBName=DZUDA0SPSUSY; SyncDBServer=ZUDA0-SPSSQL
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp] Target Values: ApplicationPool=SharePoint Service Applic
ations; Ensure=Present; MySiteHostLocation=http://localhost; Name=SCWZUDA0SPSUPS; NoILMUsed
=True; ProfileDBName=DZUDA0SPSUSP; ProfileDBServer=ZUDA0-SPSSQL; ProxyName=SCWZUDA0SPSUPS; 
SocialDBName=DZUDA0SPSUMY; SocialDBServer=ZUDA0-SPSSQL; SyncDBName=DZUDA0SPSUSY; SyncDBServ
er=ZUDA0-SPSSQL; Verbose=True
COMMENTAIRES : [SPS15DEV01]: LCM:  [ End    Test     ]  [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp]  in 5.5000 seconds.
COMMENTAIRES : [SPS15DEV01]: LCM:  [ Skip   Set      ]  [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp]
COMMENTAIRES : [SPS15DEV01]: LCM:  [ End    Resource ]  [[SPUserProfileServiceApp]APPLICATI
ON_SpsSvcAppUserProfileServiceApp]
COMMENTAIRES : [SPS15DEV01]: LCM:  [ Start  Resource ]  [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection]
COMMENTAIRES : [SPS15DEV01]: LCM:  [ Start  Test     ]  [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection]
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Importing the module MSFT_SPUserProfileSyncConne
ction in force mode.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Importing the module MSFT_SPUserProfileSyncConne
ction in force mode.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Testing for user profile service sync connection
 coquefredouille
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Getting user profile service sync connection coq
uefredouille
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Executing as the local run as user CHLOROPHYLLE\
CSAPTTD10SPSFFP
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Leaving BeginProcessing Method of Get-SPServiceA
pplication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Leaving ProcessRecord Method of Get-SPServiceApp
lication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Leaving EndProcessing Method of Get-SPServiceApp
lication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Getting SPContext for Proxy group SPServiceAppli
cationProxyGroup
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Current Values: ConnectionCredentials=; Connecti
onType=; Ensure=Absent; ExcludedOUs=; Force=; Forest=; IncludedOUs=; Name=coquefredouille; 
Port=; Server=; UseDisabledFilter=; UserProfileService=; UseSSL=
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Target Values: ConnectionCredentials=System.Mana
gement.Automation.PSCredential; ConnectionType=ActiveDirectory; Ensure=Present; ExcludedOUs
=(OU=Business,OU=Users,OU=SharePoint,DC=chlorophylle,DC=coquefredouille,DC=ovh); Force=Fals
e; Forest=chlorophylle.coquefredouille.ovh; IncludedOUs=(OU=Users,OU=SharePoint,DC=chloroph
ylle,DC=coquefredouille,DC=ovh); Name=coquefredouille; UseDisabledFilter=True; UserProfileS
ervice=SCWZUDA0SPSUPS; Verbose=True
COMMENTAIRES : [SPS15DEV01]: LCM:  [ End    Test     ]  [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection]  in 0.7650 seconds.
COMMENTAIRES : [SPS15DEV01]: LCM:  [ Start  Set      ]  [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection]
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Importing the module MSFT_SPUserProfileSyncConne
ction in force mode.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Importing the module MSFT_SPUserProfileSyncConne
ction in force mode.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Setting user profile service sync connection coq
uefredouille
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] UseSSL is not specified. Assuming that SSL is no
t required.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] NOTE: The UseDisabledFilter parameter is ignored
 in SharePoint 2013.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Executing as the local run as user CHLOROPHYLLE\
CSAPTTD10SPSFFP
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Importing function 'Get-SPDscADSIObject'.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Importing function 'Get-TargetResource'.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Importing function 'Set-TargetResource'.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Importing function 'Test-TargetResource'.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Leaving BeginProcessing Method of Get-SPServiceA
pplication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Leaving ProcessRecord Method of Get-SPServiceApp
lication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Leaving EndProcessing Method of Get-SPServiceApp
lication.
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Getting SPContext for Proxy group SPServiceAppli
cationProxyGroup
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] retrieving UserProfileConfigManager
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Creating a new connection
COMMENTAIRES : [SPS15DEV01]:                            [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection] Creating the new connection via object model (SP
2013)
COMMENTAIRES : [SPS15DEV01]: LCM:  [ End    Set      ]  [[SPUserProfileSyncConnection]APPLI
CATION_SpsSvcAppUserProfileSyncConnection]  in 1.2970 seconds.
PowerShell DSC resource MSFT_SPUserProfileSyncConnection  failed to execute 
Set-TargetResource functionality with error message: Exception calling 
"AddActiveDirectoryConnection" with "10" argument(s): "MOSS MA not found." 
    + CategoryInfo          : InvalidOperation : (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
COMMENTAIRES : [SPS15DEV01]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [] 
   , CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
COMMENTAIRES : L’opération « Invoquer une méthode CIM » est terminée.
COMMENTAIRES : Le temps nécessaire à l'exécution de la tâche de configuration est de 8.916 
secondes
`
