### ISSUE TITLE
MSFT_SPFeature Get-TargetResource returns typo in param name

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#481]
**Details of the scenario you try and problem that is occurring:**
The Get-TargetResource function of the MSFT_SPFeature resource has a typo in the return param name "InstallAccount". The following return block:

return @{
            Name = $params.Name
            FeatureScope = $params.FeatureScope
            Url = $params.Url
            **InstalAcount** = $params.InstallAccount
            Ensure = $currentState
            Version = $featureAtScope.Version
        }

Is missing a 2nd 'l' in "InstallAccount".

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
WMF 4 / Win 2012 R2

**Version of the DSC module you're using:**
1.5.0.0

**Comment by ykuijs** [comment]
This was also fixed in PR #491

**Comment by NikCharlebois** [comment]
@BrianFarnhill  @ykuijs  Somehow the issue still exsits on the current branch. was the PR even approved? Thanks

**Comment by NikCharlebois** [comment]
@BrianFarnhill @ykuijs ok, I figured this one out. It was partially fixed in 1.6.0.0. 

In 1.5.0.0 is was showing as InstalAcount, therefore missing both an 'l' and a 'c'. We've fixed the missing 'c' in 1.6.0.0., but it is still missing an 'l'.

V1.6.0.0 has it returned as "InstalAccount" now

**Comment by ykuijs** [comment]
I am on it, will be fixed in a bugfix PR

**Comment by BrianFarnhill** [comment]
This has been merged to dev and will ship in our next release, closing this issue
