### ISSUE TITLE
Improvement: Get-TargetResource for MSFT_SPManagedMetadataServiceApp throws confusing error

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/SharePointDsc#597]
**Details of the scenario you try and problem that is occurring:**
When calling the Get-TargetResource method for MSFT_SPManagerMetadataServiceApp, if the Managed Metadata Service is disabled on the farm, it throws the following error:

ForEach-Object : Cannot validate argument on parameter 'Identity'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At line:98 char:62
+ ... ion.TermStores[0].TermStoreAdministrators | ForEach-Object -Process {
+                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ForEach-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.ForEachObjectCommand

It would be nice to have something in the resource that catches the fact that the service is not enabled and throws a friendly and meaningful error.

**The DSC configuration that is using the resource:**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
SP2013/Windows Server 2012 R2/WMF 5.1

**Version of the DSC module you're using:**
1.6.0.0

**Comment by BrianFarnhill** [comment]
Let me clarify here - you mean when there is a service app, but the service instance isn't running?

**Comment by NikCharlebois** [comment]
@BrianFarnhill  correct. Let's say the service instance was stopped by mistake, then the Get-Targetresource will always throw this generic error

**Comment by BrianFarnhill** [comment]
OK cool, so we just need to put an error trap around it to let you know that it couldn't get the taxonomy session object and to check that its running. I'll put this on the backlog

**Comment by ykuijs** [comment]
@BrianFarnhill Hasn't this been fixed in PR #598?

**Comment by BrianFarnhill** [comment]
@ykuijs No this is a different error message and different scenario

**Comment by DarenDaigle** [comment]
With 1.7.0.0, even with the service app with a dependency on the instance it will still fail.
I had to comment out that line to make the resource comeback clean.  And there are no errors showing up when it happens.

**Comment by ykuijs** [comment]
Closed with PR 660
