### ISSUE TITLE
Invalid parameters error for spshelladmins and SPWebApplication with latest sharepointdsc

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SharePointDsc#711]
Context: After I download the latest sharepoint DSC module, encountered below issues.
Issue 1:

"At line:489 char:13 + AllContentDatabases = $true + ~~~~~~~~~~~~~~~~~~~ The member 'AllContentDatabases' is not valid. Valid members are 'AllDatabases', 'Databases', 'DependsOn', 'InstallAccount', 'Members', 'MembersToExclude', 'MembersToInclude', 'Name', 'PsDscRunAsCredential'. 

DSC configuration :
SPShellAdmins SharePointShellAdmins
        {           
            
            Name                 = "SharePointShellAdmins"
            Members     = $AllNodes.AdministratorsGroup
            #AllContentDatabases  = $true
            ContentDatabases    = @(
                    @(MSFT_SPContentDatabasePermissions {
                        Name = "SP2019_Content"
                        Members = $AllNodes.AdministratorsGroup
                    })
                    )
            PsDscRunAsCredential = $domjoincreds
        }

Issue 2:
At line:570 char:13 + AuthenticationMethod = "NTLM"; The member 'AuthenticationMethod' is not valid. Valid members are 'AllowAnonymous', 'ApplicationPool', 'ApplicationPoolAccount', 'DatabaseName', 'DatabaseServer', 'DependsOn', 'Ensure', 'HostHeader', 'InstallAccount', 'Name', 'Path', 'Port', 'PsDscRunAsCredential

SPWebApplication SP2019  
        {
            DatabaseName = "SP2019_Content";  
            Url = "http://" + $AllNodes.NodeName + "/";    
            ApplicationPool =  "SharePoint Service Applications"#"SP2019-AppPool";           
            Path = "C:\inetpub\wwwroot\wss\VirtualDirectories\80";
            #UseSSL = $False;  #Make it true incase of useSSL = Yes
            AllowAnonymous = $false;
            Name = "SP2019";
            AuthenticationMethod = "NTLM";  
            PsDSCRunAsCredential = $domjoincreds 
            ApplicationPoolAccount = $sp997wapcreds.UserName;
            Ensure = "Present";
            Port = "80"; 
            DatabaseServer = $AllNodes.NodeName;
            #AuthenticationProvider = "Windows Authentication";
        }

**Comment by rsganta** [comment]
Adding more data : 
Target Node OS: Windows 2016 with WMF 5.1
Power shell DSC Version : 2.0.0.0

**Comment by andikrueger** [comment]
Are you using an existing Configuration with the latest SharePoint version? There were several breaking changes with Version 2 of SharePoint Dsc. 

The SPShellAdmins Resource has no parameter "AllContentDatabases". The equivalent parameter is: AllDatabases. See: https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.schema.mof

The SPWebapplication got changed in Version 2. Please your the SPWebAppAuthentication resource in this case: https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/Examples/Resources/SPWebAppAuthentication/1-Example.ps1

**Comment by rsganta** [comment]
Thank you .
Yes, I am using existing configuration against latest SharePoint version.  I believe I tried with AllDatabases but somehow it failed.

Can I  enforce to install old module in my Azure portal ?  Also, how can I see the list of changes in the latest version?

**Comment by andikrueger** [comment]
You can find information about the breaking changes in the [SharePoint DSC Blog](https://techcommunity.microsoft.com/t5/SharePointDsc/New-release-SharePointDsc-v2-0-is-a-fact/ba-p/138409)

Are you using Azure Automation and the modules there? If yes: use the following PowerShell cmdlet to add the module to the modules of your azure Automation account:
[New-AzureRmAutomationModule](https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/New-AzureRmAutomationModule?view=azurermps-5.1.1) 

And use this source Link: https://github.com/PowerShell/SharePointDsc/archive/1.9.0.0-PSGallery.zip

**Comment by rsganta** [comment]
Yes, I am using Azure Automation and the modules..

I have tried to download the sharepointdsc version 1.9.0.0  and tried to upload the zip to azure modules. After successful upload and while importing the content , encountered the below error.

Error importing the module SharePointDsc. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.

**Comment by andikrueger** [comment]
Did you try the cmdlet?

If you try to upload a module using the Azure Portal Website there are some changes needed. Please unzip the file and zip the contents of the Folder 1.9.0.0 again. Try to upload this newly created zip file. All files of the 1.9.0.0 folder have to placed in the root of this new ZIP file. Hope this helps.

**Comment by rsganta** [comment]
I did not use the cmdlet and trying to upload the module using azure website. Tried few times by deleting the existing 2.0.0.0 module and upload 1.9.0.0 zip file but failed. Still working on it.

**Comment by rsganta** [comment]
Any content files needs to be removed ?

**Comment by rsganta** [comment]
Also on my older machine I have this module with 1.9.0.0 . If I can copy that module on to my targeted node and upload(after zip the contents) to azure portal might help to proceed further.

**Comment by rsganta** [comment]
I am able to successfully upload it by using the content from my older machine. thanks for your help.

**Comment by ykuijs** [comment]
I realized I didn't update the Wiki content yet to reflect all v2.0 changes. I just corrected this, so the current documentation is now in there.

Good to hear you were able to get 1.9 to work in your environment. But to get back to the 2.0 issue:
Are you 100% sure you used the correct parameters with 2.0 of the resource? If so, we might have an issue in this release which I would like to fix.

**Comment by rsganta** [comment]
I am still testing my config with 1.9 .. It was all working fine before I update to 2.0. I am still unable to use 2.0 fully as I was running into couple of issues which were brought up in starting of this thread. Will keep you posted.  
Some process is causing my sharepoint install to restart every 5 minutes. Still trying it figure out what went wrong since yesterday to today.

**Comment by rsganta** [comment]
I tried multiple options but no luck so far.
Option 1: Tried to fix the build share in the IE-> Security->Localintranet. . This even did not help and it restarted machine all the time when SPInstall comes.

Option 2:  I triggered new VM to avoid all stale processes in the previous machine. I have noticed few installers e.g. SSMS.exe and .net 4.7 installer  etc. are running through they were installed . Hence, I have killed those processes and went straight to sharepoint installation. Even then, my node is rebooting.

I am going to try 3 rd option by removing all sql related blocks from my config and install only sharepoint.

**Comment by rsganta** [comment]
I have tried 3rd option too and could not identify the real source of truth which is blocking sharepoint installation on my VM. It's very interesting , It was working until yesterday and all of sudden started seeing these issues. Since I am learning very first time on DSC, I would greatly appreciate insights to unblock this issue.

**Comment by rsganta** [comment]
Finally I could see sharepoint installation succeeded on my machine.  Not sure whether  3rd option helped (or) normally it is taking more time to complete the installation. Thank you for your time. I am still using 1.9.0.0 sharepoint dsc version.

**Comment by ykuijs** [comment]
Closing this issue since you were able to install SP as expected.
